### ISSUE TITLE
Clicking top or bottom nav link doesn't always scroll the page to the top

### ISSUE THREAD

**Issue by alykat** [nprapps/syria#104]
Sometimes it jumps to the next chapter, but at the bottom of the page. Haven't figured out a pattern to when this happens.

**Comment by alykat** [comment]
Seems to happen when I go back to a chapter I've already read.

**Comment by eads** [comment]
Yeah... I noticed this earlier but didn't think it a bug, per se, because we didn't actually have nav. The browser retains the container scroll position. But I know how to fix it!
