### ISSUE TITLE
Analytics?

### ISSUE THREAD

**Issue by alykat** [nprapps/syria#115]
We talked about this being an experiment of sorts. What should we be measuring / event-tracking?

**Comment by livlab** [comment]
Navigating between chapters: 
- Do people read in order? 
- Do they jump ahead? 
- Do they return to read through if they jump ahead? 
- Do they return to other chapters after completion? Why?
- Do they prefer Next or the linked Sentence to proceed to next chapter (probably needed a special event tracking to distinguish. Too late to add?)

Traffic: 
- Does it drive traffic to other refugee stories (listed at the end)?

**Comment by brianboyer** [comment]
tracking chapter clicks, completion rate, that's good enough for today
