### ISSUE TITLE
Can't scroll past the chart on Russia chapter in iPhone

### ISSUE THREAD

**Issue by livlab** [nprapps/syria#146]
Please test on an actual device. Could not scroll past this point on xCode Simulator for iPhone 5s, iOs 8.1

![screenshot 2015-02-13 14 31 16](https://cloud.githubusercontent.com/assets/1936365/6193846/28ffc8b0-b38d-11e4-96e6-2daf17579a2e.png)

**Comment by alykat** [comment]
woo!
