### ISSUE TITLE
Device testing: iPad

### ISSUE THREAD

**Issue by eads** [nprapps/syria#17]

**Comment by livlab** [comment]
Tested on iPad 2, iOS 8.1 (xCode Simulator). Found issue #140.

Tested on an old iPad (1st generation), which only runs iOS 5.1.1. (and can't upgrade) and everything works, but scrolling the story is very choppy. I don't know if you care about this device segment, but thought I'd let you know just in case.

**Comment by livlab** [comment]
Opened #142
