### ISSUE TITLE
Update Twitter Card tags

### ISSUE THREAD

**Issue by eads** [nprapps/syria#3]
Validator: https://dev.twitter.com/docs/cards/validation/validator
working w/ @kainazamaria

**Comment by beckylettenberger** [comment]
Suggestion:
Amid civil war, four stories of families struggling to stay together.

**Comment by beckylettenberger** [comment]
![syria_twitter](https://cloud.githubusercontent.com/assets/6115291/6195420/f249aa0c-b39b-11e4-8ef5-23c96cf875a8.jpg)
