### ISSUE TITLE
Text legibility during first image load

### ISSUE THREAD

**Issue by livlab** [nprapps/syria#92]
The background image loads slowly on first visit so the text is not very legible during load.  If this is acceptable, perhaps a different background color for more contrast with text could make if sufficiently legible until the image loads.

Occurring on:
- Android Chrome
- iPhone Safari
- Desktop Safari
- Desktop Chrome
- Desktop Firefox

**Comment by livlab** [comment]
@eads I thought simply adding _background-color: #000;_ to _.full-block-cell_ class in start.less would do the trick, but it prevents the background image from showing. I'm not sure how to reverse the load order. Coach?

**Comment by alykat** [comment]
Try adding it to `.start` instead?

**Comment by livlab** [comment]
That was it, thank you! Now I understand the app template better. ^_^

**Comment by livlab** [comment]
@alykat Simply adding to where .start was makes all content background black, so I repeated slide again separately. Would love you to take a look to see if this is a legitimate way to do it. It works, but I don't know if I'm writing "good" CSS there. Works across browsers.
