### ISSUE TITLE
Linked quote to next chapter lacks visual indication that it is clickable

### ISSUE THREAD

**Issue by livlab** [nprapps/syria#94]
Across all chapters, the linked quote at the bottom does not look like a link (no visual indication that it is clickable); on hover cursor does not change to indicate its linked and color doesn't differentiate from quote text to indicate its a link (the link does work though).

Occurring on:
- Android Chrome
- iPhone Safari
- Desktop Safari
- Desktop Chrome
- Desktop Firefox

**Comment by alykat** [comment]
Fixed in e8ebeaeb59c0da3ced49ba291b1361530aeac1b1
